name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  test:
    uses: go-simpler/.github/.github/workflows/test.yml@main
  lint:
    uses: go-simpler/.github/.github/workflows/lint.yml@main
  vuln:
    uses: go-simpler/.github/.github/workflows/vuln.yml@main
